spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: vinicius
    password: password
    url: jdbc:postgresql://localhost:5432/apiorders
  jpa:
    hibernate:
      ddl-auto: create